---
- hosts: all
  become: yes
  tasks:
    - name: Install required apt packages
      apt:
        update_cache: yes
        pkg:
          - libpq-dev
          - build-essential
          - libcurl4-gnutls-dev
          - libxml2-dev
          - libssl-dev
          - apache2
          - apache2-dev
          - systemd

    - name: Install apache2 modules
      apache2_module:
        name: mod_wsgi
        state: present
      notify:
        - restart apache2

    - name: Ensure apache2 is running
      service:
        name: apache2
        state: started

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
