---
- name: Download mod_wsgi source code
  get_url:
    url: "https://github.com/GrahamDumpleton/mod_wsgi/archive/{{ wsgi_version }}.tar.gz"
    dest: "{{ wsgi_package_path }}"

- name: Untar the source archive
  unarchive:
    src: "{{ wsgi_package_path}}"
    dest: "{{ wsgi_download_dir }}"
    creates: "{{ wsgi_extract_path }}/configure"
    remote_src: yes

- name: Run configure
  shell: "./configure --with-python=/usr/bin/python3"
  args:
    chdir: "{{ wsgi_extract_path }}"
    creates: "{{ wsgi_extract_path }}/Makefile"

- name: Run make
  command: make
  args:
    chdir: "{{ wsgi_extract_path }}"
    creates: "{{ wsgi_extract_path }}/src/server/.libs/mod_wsgi.so"

- name: Run make install
  command: make install
  args:
    chdir: "{{ wsgi_extract_path }}"
    creates: "{{ apache_libexecdir }}/mod_wsgi.so"
